### ISSUE TITLE
Weird Colored Clouds

### ISSUE THREAD

**Issue by aprilkenopsia** [mineblock11/FabulousClouds#10]
my clouds are pink... but not in the right way
i opened a 1.17 world and that happened (using 0.2.1 on 1.17.1)

![image](https://user-images.githubusercontent.com/28115928/129812621-ec2a0024-ee3e-463c-8d54-f5f026bd7962.png)

i honestly have no idea what happened here

**Comment by aprilkenopsia** [comment]
it changes color depending on which direction i look

**east**
![image](https://user-images.githubusercontent.com/28115928/129812997-7aed3833-a326-4165-928a-4b7360b3e5de.png)

**South and south east ?**
![image](https://user-images.githubusercontent.com/28115928/129813069-db5c7656-b681-441c-9284-c6d8392e5b04.png)
![image](https://user-images.githubusercontent.com/28115928/129813089-dc0f5802-5960-49bc-88f9-337ae3446c26.png)

when i look above 28.1 to 30.1 it goes green
![image](https://user-images.githubusercontent.com/28115928/129813182-a922314d-9d4e-43df-93bc-6549d467b6e7.png)

worth nothing i use sodium

**Comment by aprilkenopsia** [comment]
the green thing happens in some other angles too

**Comment by misterslime** [comment]
Try deleting the config. The weird colors could be because the vibrance_intensity option isn't in the config.

**Comment by aprilkenopsia** [comment]
![image](https://user-images.githubusercontent.com/28115928/129832044-e215ffbe-9079-4185-b7c5-092e544141ec.png)
worked!
