### ISSUE TITLE
Clouds are not centered

### ISSUE THREAD

**Issue by xpopy** [mineblock11/FabulousClouds#11]
![image](https://user-images.githubusercontent.com/3540971/129966049-f7e28959-9faa-4a8a-93fa-63385e08efbb.png)

Using render distance of 32, one cloud layer with an offset of 400 and scale 1.5

On a side note: Idk if its possible, but it would be great if we could have a higher cloud render distance than the chunk render distance. I like to have clouds pretty far up but they get cut off so I barely see them

**Comment by K0-RR** [comment]
>On a side note: Idk if its possible, but it would be great if we could have a higher cloud render distance than the chunk render distance. I like to have clouds pretty far up but they get cut off so I barely see them

You are literally reading my mind! +1 to this feature as this is so annoying in vanilla.
