### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by efffauw** [mineblock11/FabulousClouds#19]
https://bytebin.lucko.me/FdSzDUtjrF

**Comment by taciturnaxolotl** [comment]
I have this error to.
https://crashy.net/VaetZCVFwqoaIdjVUPmB

**Comment by Tartarus6** [comment]
me too, it happens exactly when the world opens.
https://bytebin.lucko.me/ekIveph1qn

**Comment by Heamaci** [comment]
I just wanted to add that I also get this error.

**Comment by misterslime** [comment]
Sorry I took so long to respond! I've been busy with school work and haven't had much time to work on this mod. I'll start working on fixing this today.

**Comment by taciturnaxolotl** [comment]
Thank you!
